# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Nonewa Provider' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Nonewa Provider
  pod 'Alamofire', '~> 4.5'
  pod 'SwiftyJSON'
  pod 'AlamofireImage', '~> 3.3'
  target 'Nonewa ProviderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Nonewa ProviderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
