-- Write a query that prints a list of employee names (i.e.: the name attribute)
-- for employees in Employee having a salary greater than $2000 per month who have been
--  employees for less than 10 months. Sort your result by ascending employee_id.
-- Input Format
-- The Employee table containing employee data for a company is described as follows:
-- Sample Output
-- Angela
-- Michael
-- Todd
-- Joe
-- Explanation
-- Angela has been an employee for  month and earns  per month.
-- Michael has been an employee for  months and earns  per month.
-- Todd has been an employee for  months and earns  per month.
-- Joe has been an employee for  months and earns  per month.
-- We order our output by ascending employee_id
select name from employee where salary > 2000 and months < 10 order by employee_id
-- Rose
-- Patrick
-- Lisa
-- Amy
-- Pamela
-- Jennifer
-- Julia
-- Kevin
