-- Query the sum of the populations for all Japanese cities in CITY.
-- The COUNTRYCODE for Japan is JPN.
-- nearest integer.
-- Input Format
--       CITY
-- Field          Type
-- ID             NUMBER
-- NAME           Varchar2(17)
-- COUNTRYCODE    Varchar2(3)
-- DISTRICT       Varchar2(20)
-- POPULATIONS    NUMBER
select sum(population) from city where countrycode = 'JPN'
