-- Samantha was tasked with calculating the average monthly salaries for all
-- employees in the EMPLOYEES table, but did not realize her keyboard's 0 key was
-- broken until after completing the calculation. She wants your help finding the
-- difference between her miscalculation (using salaries with any zeroes removed),
-- and the actual average salary.
--
-- Write a query calculating the amount of error (i.e.: actual - miscalculated
--    average monthly salaries), and round it up to the next integer.
--
-- Input Format
--
-- The EMPLOYEES table is described as follows:
-- Field          Type
-- ID             NUMBER
-- NAME           Varchar2(17)
-- Salary         NUMBER
--
-- Sample Output
-- 2061
-- Explanation
-- The table below shows the salaries without zeroes as they were entered by Samantha:
select ceil(avg(salary)-avg(replace(salary,'0',''))) from employees
