-- Query the smallest Northern Latitude (LAT_N) from STATION that is greater than
-- 38.7880 . Round your answer to 4 decimal places.
-- Input Format
-- The STATION table is described as follows:
--       STATION
-- Field          Type
-- ID             NUMBER
-- CITY           Varchar2(21)
-- STATE          Varchar2(2)
-- LAT_N          NUMBER
-- LONG_W         NUMBER
-- where LAT_N is the northern latitude and LONG_W is the western longitude.
select round(lat_n, 4) from station where lat_n > 38.7880 order by lat_n limit 1
-- 38.8526
