-- Query a list of CITY and STATE from the STATION table.
-- Input Format
-- The STATION table is described as follows:
--       STATION
-- Field          Type
-- ID             NUMBER
-- CITY           Varchar2(21)
-- STATE          Varchar2(2)
-- LAT_N          NUMBER
-- LONG_W         NUMBER
-- where LAT_N is the northern latitude and LONG_W is the western longitude.
SELECT CITY, STATE FROM STATION
-- Acme LA
-- Addison MI
-- Agency MO
-- Aguanga CA
-- Alanson MI
-- Alba MI
-- Albany CA
-- Albion IN
-- Algonac MI
-- Aliso Viejo CA
-- Allerton IA
-- Alpine AR
-- Alton MO
-- Amazonia MO
-- Amo IN
-- Andersonville GA
-- Andover CT
-- Anthony KS
-- Archie MO
-- Arispe IA
