-- Query the list of CITY names starting with vowels (i.e., a, e, i, o, or u)
-- from STATION. Your result cannot contain duplicates.
-- Input Format
-- The STATION table is described as follows:
--       STATION
-- Field          Type
-- ID             NUMBER
-- CITY           Varchar2(21)
-- STATE          Varchar2(2)
-- LAT_N          NUMBER
-- LONG_W         NUMBER
-- where LAT_N is the northern latitude and LONG_W is the western longitude.
SELECT DISTINCT city FROM station WHERE city REGEXP "^[aeiou].*";
-- Acme
-- Addison
-- Agency
-- Aguanga
-- Alanson
-- Alba
-- Albany
-- Albion
